import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import CartProvider from "@/components/provider";
import ShoppingCartModal from "@/components/ShoppingCartModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <div className=" bg-neutral-900">
            <Navbar />
            <ShoppingCartModal/>
            {children}
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
